-- TAŞINDI → supabase/migrations/20240101000000_init.sql
--
-- Bu dosya v1 şemasını içeriyordu ama `migrations/` dışındaydı, dolayısıyla
-- `supabase db reset` onu hiç uygulamıyordu: profiles, mistakes, mistake_type
-- enum'u ve mistake-photos kovası yaratılmadan sonraki tüm göçler boş bir
-- veritabanına uygulanıyordu. İçerik göçlerin en başına taşındı.
--
-- Burası bilerek boş bırakıldı (yalnızca bu not). Şemayı arıyorsanız:
--   supabase/migrations/20240101000000_init.sql
