-- MEB sorularını yeni MEBİ ANA KONU seviyesine dağıtır (TYT + AYT).
-- source='meb'; eski etiket -> yeni konu. İki kez çalıştırmak güvenli.
begin;
update public.mistakes set concept='Canlıların Ortak Özellikleri' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Canlıların Ortak Özellikleri';
update public.mistakes set concept='Canlıların Sınıflandırılması' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Canlıların Sınıflandırılması';
update public.mistakes set concept='Ekosistem Ekolojisi' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Ekosistem Ekolojisi';
update public.mistakes set concept='Canlıların Yapısında Bulunan Organik Bileşikler' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Enzimler';
update public.mistakes set concept='Güncel Çevre Sorunları' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Güncel Çevre Sorunları';
update public.mistakes set concept='Hücresel Yapılar ve Görevleri' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Hücre ve Organelleri';
update public.mistakes set concept='Hücre Zarından Madde Geçişleri' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Hücre Zarından Madde Geçişi';
update public.mistakes set concept='Canlıların Yapısında Bulunan İnorganik Bileşikler' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='İnorganik Bileşikler';
update public.mistakes set concept='Kalıtım' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Kalıtım';
update public.mistakes set concept='Ekosistem Ekolojisi' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Madde Döngüleri';
update public.mistakes set concept='Mayoz' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Mayoz ve Eşeyli Üreme';
update public.mistakes set concept='Hücre Döngüsü ve Mitoz' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Mitoz ve Eşeysiz Üreme';
update public.mistakes set concept='Canlıların Yapısında Bulunan Organik Bileşikler' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Nükleik Asitler';
update public.mistakes set concept='Canlıların Yapısında Bulunan Organik Bileşikler' where source='meb' and exam='TYT' and subject='Biyoloji' and concept='Organik Bileşikler (Karbonhidrat-Lipit-Protein)';
update public.mistakes set concept='İklim Bilimi' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Atmosfer ve Sıcaklık';
update public.mistakes set concept='İklim Bilimi' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Basınç ve Rüzgârlar';
update public.mistakes set concept='Bölgeler ve Ülkeler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Bölgeler';
update public.mistakes set concept='İnsan ve Çevre' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Çevre ve Toplum';
update public.mistakes set concept='Dünya''nın Yapısı ve Oluşum Süreci' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Dış Kuvvetler';
update public.mistakes set concept='Coğrafya Bilimi, İnsan ve Doğa' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Doğa ve İnsan';
update public.mistakes set concept='Afetler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Doğal Afetler';
update public.mistakes set concept='Dünya''nın Şekli ve Hareketleri' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Dünya''nın Şekli ve Hareketleri';
update public.mistakes set concept='Nüfus, Göç, Ekonomik Faaliyetler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Ekonomik Faaliyetler';
update public.mistakes set concept='Nüfus, Göç, Ekonomik Faaliyetler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Göç';
update public.mistakes set concept='Harita Bilimi' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Harita Bilgisi';
update public.mistakes set concept='Dünya''nın Yapısı ve Oluşum Süreci' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='İç Kuvvetler';
update public.mistakes set concept='İklim Bilimi' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Nem-Yağış-Buharlaşma';
update public.mistakes set concept='Nüfus, Göç, Ekonomik Faaliyetler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Nüfus';
update public.mistakes set concept='Su Kaynakları, Topraklar, Bitkiler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Su Kaynakları';
update public.mistakes set concept='Su Kaynakları, Topraklar, Bitkiler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Toprak ve Bitki Örtüsü';
update public.mistakes set concept='Yerleşmeler' where source='meb' and exam='TYT' and subject='Coğrafya' and concept='Yerleşme';
update public.mistakes set concept='Ahlaki Tutum Davranışlar' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Ahlaki Tutum ve Davranışlar';
update public.mistakes set concept='Allah İnsan İlişkisi' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Allah-İnsan İlişkisi';
update public.mistakes set concept='Bilgi ve İnanç' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Bilgi ve İnanç';
update public.mistakes set concept='Din ve Hayat' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Din ve Hayat';
update public.mistakes set concept='Din ve İslam' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Din ve İslam';
update public.mistakes set concept='Gençlik ve Değerler' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Gençlik ve Değerler';
update public.mistakes set concept='Gönül Coğrafyamız' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Gönül Coğrafyamız';
update public.mistakes set concept='Hz. Muhammed ve Gençlik' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='Hz. Muhammed ve Gençlik';
update public.mistakes set concept='İslam Düşüncesinde İtikadi, Siyasi ve Fıkhi Yorumlar' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='İslam Düşüncesinde Yorumlar';
update public.mistakes set concept='İslam ve İbadet' where source='meb' and exam='TYT' and subject='Din Kültürü' and concept='İslam ve İbadet';
update public.mistakes set concept='Ahlak Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Ahlak Felsefesi';
update public.mistakes set concept='Bilgi Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Bilgi Felsefesi';
update public.mistakes set concept='Bilim Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Bilim Felsefesi';
update public.mistakes set concept='Din Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Din Felsefesi';
update public.mistakes set concept='Felsefeyi Tanıma' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Felsefenin Konusu';
update public.mistakes set concept='Sanat Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Sanat Felsefesi';
update public.mistakes set concept='Siyaset Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Siyaset Felsefesi';
update public.mistakes set concept='Varlık Felsefesi' where source='meb' and exam='TYT' and subject='Felsefe' and concept='Varlık Felsefesi';
update public.mistakes set concept='Hareket ve Kuvvet' where source='meb' and exam='TYT' and subject='Fizik' and concept='Basit Makineler';
update public.mistakes set concept='Basınç ve Kaldırma Kuvveti' where source='meb' and exam='TYT' and subject='Fizik' and concept='Basınç';
update public.mistakes set concept='Dalgalar' where source='meb' and exam='TYT' and subject='Fizik' and concept='Dalgalar (Temel)';
update public.mistakes set concept='Hareket ve Kuvvet' where source='meb' and exam='TYT' and subject='Fizik' and concept='Doğrusal Hareket';
update public.mistakes set concept='Optik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Düzlem Ayna';
update public.mistakes set concept='Elektrik ve Manyetizma' where source='meb' and exam='TYT' and subject='Fizik' and concept='Elektrik Akımı ve Devreler';
update public.mistakes set concept='Elektrostatik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Elektrostatik';
update public.mistakes set concept='Fizik Bilimine Giriş' where source='meb' and exam='TYT' and subject='Fizik' and concept='Fizik Bilimine Giriş';
update public.mistakes set concept='Enerji' where source='meb' and exam='TYT' and subject='Fizik' and concept='İş-Güç-Enerji';
update public.mistakes set concept='Isı ve Sıcaklık' where source='meb' and exam='TYT' and subject='Fizik' and concept='Isı ve Sıcaklık';
update public.mistakes set concept='Optik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Işık ve Gölge';
update public.mistakes set concept='Optik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Kırılma ve Renkler';
update public.mistakes set concept='Optik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Küresel Aynalar';
update public.mistakes set concept='Hareket ve Kuvvet' where source='meb' and exam='TYT' and subject='Fizik' and concept='Kuvvet ve Denge (Vektörler)';
update public.mistakes set concept='Madde ve Özellikleri' where source='meb' and exam='TYT' and subject='Fizik' and concept='Madde ve Özellikleri';
update public.mistakes set concept='Optik' where source='meb' and exam='TYT' and subject='Fizik' and concept='Mercekler';
update public.mistakes set concept='Elektrik ve Manyetizma' where source='meb' and exam='TYT' and subject='Fizik' and concept='Mıknatıslar ve Manyetik Alan';
update public.mistakes set concept='Basınç ve Kaldırma Kuvveti' where source='meb' and exam='TYT' and subject='Fizik' and concept='Sıvıların Kaldırma Kuvveti';
update public.mistakes set concept='Dalgalar' where source='meb' and exam='TYT' and subject='Fizik' and concept='Yay ve Su Dalgaları';
update public.mistakes set concept='Üçgenin Yardımcı Elemanları' where source='meb' and exam='TYT' and subject='Geometri' and concept='Açıortay';
update public.mistakes set concept='Çokgenler' where source='meb' and exam='TYT' and subject='Geometri' and concept='Çokgenler';
update public.mistakes set concept='Dik Üçgen ve Trigonometri' where source='meb' and exam='TYT' and subject='Geometri' and concept='Dik Üçgen';
update public.mistakes set concept='Özel Dörtgenler' where source='meb' and exam='TYT' and subject='Geometri' and concept='Dikdörtgen ve Kare';
update public.mistakes set concept='Üçgenin Yardımcı Elemanları' where source='meb' and exam='TYT' and subject='Geometri' and concept='Kenarortay';
update public.mistakes set concept='Özel Dörtgenler' where source='meb' and exam='TYT' and subject='Geometri' and concept='Paralelkenar';
update public.mistakes set concept='Üçgenlerde Temel Kavramlar' where source='meb' and exam='TYT' and subject='Geometri' and concept='Üçgende Açılar';
update public.mistakes set concept='Üçgenin Alanı' where source='meb' and exam='TYT' and subject='Geometri' and concept='Üçgende Alan';
update public.mistakes set concept='Üçgenlerde Eşlik ve Benzerlik' where source='meb' and exam='TYT' and subject='Geometri' and concept='Üçgende Benzerlik';
update public.mistakes set concept='Asitler, Bazlar ve Tuzlar' where source='meb' and exam='TYT' and subject='Kimya' and concept='Asit-Baz';
update public.mistakes set concept='Atom ve Periyodik Sistem' where source='meb' and exam='TYT' and subject='Kimya' and concept='Atomun Yapısı';
update public.mistakes set concept='Doğa ve Kimya' where source='meb' and exam='TYT' and subject='Kimya' and concept='Doğa ve Kimya';
update public.mistakes set concept='Kimyasal Türler Arası Etkileşimler' where source='meb' and exam='TYT' and subject='Kimya' and concept='İyonik Bağ';
update public.mistakes set concept='Karışımlar' where source='meb' and exam='TYT' and subject='Kimya' and concept='Karışımlar';
update public.mistakes set concept='Kimya Bilimi' where source='meb' and exam='TYT' and subject='Kimya' and concept='Kimya Bilimine Giriş';
update public.mistakes set concept='Kimya Her Yerde' where source='meb' and exam='TYT' and subject='Kimya' and concept='Kimya Her Yerde';
update public.mistakes set concept='Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar' where source='meb' and exam='TYT' and subject='Kimya' and concept='Kimyanın Temel Kanunları';
update public.mistakes set concept='Kimyasal Türler Arası Etkileşimler' where source='meb' and exam='TYT' and subject='Kimya' and concept='Kovalent Bağ';
update public.mistakes set concept='Maddenin Hâlleri' where source='meb' and exam='TYT' and subject='Kimya' and concept='Maddenin Halleri';
update public.mistakes set concept='Kimyasal Türler Arası Etkileşimler' where source='meb' and exam='TYT' and subject='Kimya' and concept='Metalik Bağ ve Zayıf Etkileşimler';
update public.mistakes set concept='Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar' where source='meb' and exam='TYT' and subject='Kimya' and concept='Mol Kavramı ve Hesaplamalar';
update public.mistakes set concept='Atom ve Periyodik Sistem' where source='meb' and exam='TYT' and subject='Kimya' and concept='Periyodik Sistem';
update public.mistakes set concept='Birinci Dereceden Denklemler ve Eşitsizlikler' where source='meb' and exam='TYT' and subject='Matematik' and concept='Basit Eşitsizlikler';
update public.mistakes set concept='Bölünebilme Kuralları' where source='meb' and exam='TYT' and subject='Matematik' and concept='Bölme-Bölünebilme';
update public.mistakes set concept='Fonksiyon Kavramı ve Gösterimi' where source='meb' and exam='TYT' and subject='Matematik' and concept='Fonksiyonlar';
update public.mistakes set concept='İkinci Dereceden Bir Bilinmeyenli Denklemler' where source='meb' and exam='TYT' and subject='Matematik' and concept='İkinci Dereceden Denklemler';
update public.mistakes set concept='Merkezi Eğilim ve Yayılım Ölçüleri' where source='meb' and exam='TYT' and subject='Matematik' and concept='İstatistik';
update public.mistakes set concept='Kümelerde Temel Kavramlar' where source='meb' and exam='TYT' and subject='Matematik' and concept='Kümeler';
update public.mistakes set concept='Önermeler ve Bileşik Önermeler' where source='meb' and exam='TYT' and subject='Matematik' and concept='Mantık';
update public.mistakes set concept='Basit Olayların Olasılıkları' where source='meb' and exam='TYT' and subject='Matematik' and concept='Olasılık';
update public.mistakes set concept='Sıralama ve Seçme' where source='meb' and exam='TYT' and subject='Matematik' and concept='Permütasyon-Kombinasyon';
update public.mistakes set concept='Polinom Kavramı ve Polinomlarda İşlemler' where source='meb' and exam='TYT' and subject='Matematik' and concept='Polinomlar';
update public.mistakes set concept='Denklemler ve Eşitsizlikler ile İlgili Uygulamalar' where source='meb' and exam='TYT' and subject='Matematik' and concept='Sayı Problemleri';
update public.mistakes set concept='Sayı Kümeleri' where source='meb' and exam='TYT' and subject='Matematik' and concept='Temel Kavramlar';
update public.mistakes set concept='Üslü İfadeler ve Denklemler' where source='meb' and exam='TYT' and subject='Matematik' and concept='Üslü Sayılar';
update public.mistakes set concept='Cümle Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Cümle Türleri';
update public.mistakes set concept='Sözcük Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Edat-Bağlaç-Ünlem';
update public.mistakes set concept='Fiiller' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Fiilde Anlam (Kip-Kişi)';
update public.mistakes set concept='Fiiller' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Fiilimsi';
update public.mistakes set concept='Sözcük Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='İsim (Ad)';
update public.mistakes set concept='Noktalama İşaretleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Noktalama İşaretleri';
update public.mistakes set concept='Sözcük Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Sıfat';
update public.mistakes set concept='Yazım Kuralları' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Yazım Kuralları';
update public.mistakes set concept='Sözcük Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Zamir';
update public.mistakes set concept='Sözcük Türleri' where source='meb' and exam='TYT' and subject='Türkçe' and concept='Zarf';
update public.mistakes set concept='Beylikten Devlete Osmanlı Siyaseti (1302-1453)' where source='meb' and exam='TYT' and subject='Tarih' and concept='Beylikten Devlete Osmanlı (1302-1453)';
update public.mistakes set concept='Dünya Gücü Osmanlı (1453-1595)' where source='meb' and exam='TYT' and subject='Tarih' and concept='Dünya Gücü Osmanlı (1453-1595)';
update public.mistakes set concept='İlk ve Orta Çağlarda Türk Dünyası' where source='meb' and exam='TYT' and subject='Tarih' and concept='İlk ve Orta Çağlarda Türk Dünyası';
update public.mistakes set concept='Tarih ve Zaman' where source='meb' and exam='TYT' and subject='Tarih' and concept='İnsanlığın İlk Dönemleri';
update public.mistakes set concept='İslam Medeniyetinin Doğuşu' where source='meb' and exam='TYT' and subject='Tarih' and concept='İslam Medeniyetinin Doğuşu';
update public.mistakes set concept='Klasik Çağda Osmanlı Toplum Düzeni' where source='meb' and exam='TYT' and subject='Tarih' and concept='Klasik Çağda Osmanlı Toplum Düzeni';
update public.mistakes set concept='İlk ve Orta Çağlarda Türk Dünyası' where source='meb' and exam='TYT' and subject='Tarih' and concept='Orta Çağ''da Dünya';
update public.mistakes set concept='Beylikten Devlete Osmanlı Medeniyeti' where source='meb' and exam='TYT' and subject='Tarih' and concept='Osmanlı Medeniyeti';
update public.mistakes set concept='Sultan ve Osmanlı Merkez Teşkilatı' where source='meb' and exam='TYT' and subject='Tarih' and concept='Osmanlı Merkez Teşkilatı';
update public.mistakes set concept='Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi' where source='meb' and exam='TYT' and subject='Tarih' and concept='Selçuklu Türkiyesi';
update public.mistakes set concept='Tarih ve Zaman' where source='meb' and exam='TYT' and subject='Tarih' and concept='Tarih ve Zaman';
update public.mistakes set concept='Türk İslam Tarihindeki Siyasi Gelişmeler, Türklerin İslamiyet''i Kabulü' where source='meb' and exam='TYT' and subject='Tarih' and concept='Türklerin İslamiyet''i Kabulü';
update public.mistakes set concept='Bağışıklık Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Bağışıklık Sistemi';
update public.mistakes set concept='Bitkilerde Madde Taşınması' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Bitkilerde Taşıma-Beslenme-Terleme';
update public.mistakes set concept='Bitkilerde Eşeyli Üreme' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Bitkilerde Üreme';
update public.mistakes set concept='Bitkisel Dokular' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Bitkisel Dokular';
update public.mistakes set concept='Bitki Hormonları' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Bitkisel Hormonlar';
update public.mistakes set concept='Üriner Sistem' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Boşaltım Sistemi';
update public.mistakes set concept='İskelet Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Destek ve Hareket Sistemi';
update public.mistakes set concept='Nükleik Asitler' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='DNA Replikasyonu';
update public.mistakes set concept='Kan Dolaşımı' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Dolaşım Sistemi';
update public.mistakes set concept='Duyu Organları' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Duyu Organları';
update public.mistakes set concept='Endokrin Sistem' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Endokrin Sistem ve Hormonlar';
update public.mistakes set concept='Fotosentez' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Fotosentez';
update public.mistakes set concept='Hücresel Solunum' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Hücresel Solunum';
update public.mistakes set concept='Kemosentez' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Kemosentez';
update public.mistakes set concept='Komünite Ekolojisi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Komünite Ekolojisi';
update public.mistakes set concept='Genetik Mühendisliği ve Biyoteknoloji' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Modern Genetik Uygulamaları';
update public.mistakes set concept='Nükleik Asitler' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Nükleik Asitler';
update public.mistakes set concept='Popülasyon Ekolojisi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Popülasyon Ekolojisi';
update public.mistakes set concept='Genetik Şifre ve Protein Sentezi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Protein Sentezi';
update public.mistakes set concept='Sindirim Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Sindirim Sistemi';
update public.mistakes set concept='Sinir Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Sinir Sistemi';
update public.mistakes set concept='Solunum Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Solunum Sistemi';
update public.mistakes set concept='Üreme Sistemi' where source='meb' and exam='AYT' and subject='Biyoloji' and concept='Üreme Sistemi ve Embriyonik Gelişim';
update public.mistakes set concept='Nüfus Politikaları ve Yerleşmeler' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Beşerî Sistemler';
update public.mistakes set concept='Türkiye''nin İşlevsel Bölgeleri ve Kalkınma Projeleri' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Bölgesel Kalkınma Projeleri';
update public.mistakes set concept='Çevre Sorunları' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Çevre ve Toplum';
update public.mistakes set concept='Ekstrem Doğa Olayları ve Doğa Olaylarının Geleceği' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Doğal Afetler ve Toplum';
update public.mistakes set concept='Ekonomik Faaliyetler ve Doğal Kaynaklar' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Doğal Kaynaklar';
update public.mistakes set concept='Ekosistemlerin İşleyişi ve Özellikleri' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Doğal Sistemler (Biyoçeşitlilik)';
update public.mistakes set concept='Ekosistemlerin İşleyişi ve Özellikleri' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Ekosistem ve Madde Döngüsü';
update public.mistakes set concept='Ekonomi, Şehirleşme ve Göç' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Göç ve Şehirleşme';
update public.mistakes set concept='Küreselleşen Dünya' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Küresel Ortam: Bölgeler ve Ülkeler';
update public.mistakes set concept='Nüfus Politikaları ve Yerleşmeler' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Nüfus Politikaları';
update public.mistakes set concept='Türkiye''de Ekonomi' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye Ekonomisinin Sektörel Dağılımı';
update public.mistakes set concept='Türkiye''de Ekonomi' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye''de Madenler ve Enerji Kaynakları';
update public.mistakes set concept='Nüfus Politikaları ve Yerleşmeler' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye''de Nüfus ve Yerleşme';
update public.mistakes set concept='Türkiye''de Ekonomi' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye''de Sanayi';
update public.mistakes set concept='Türkiye''de Ekonomi' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye''de Tarım';
update public.mistakes set concept='Ulaşım, Ticaret, Turizm' where source='meb' and exam='AYT' and subject='Coğrafya' and concept='Türkiye''de Ticaret-Ulaşım-Turizm';
update public.mistakes set concept='Anadolu''da İslam' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Anadolu''da İslam';
update public.mistakes set concept='Dünya ve Ahiret' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Dünya ve Ahiret';
update public.mistakes set concept='Güncel Dinî Meseleler' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Güncel Dinî Meseleler';
update public.mistakes set concept='Hint ve Çin Dinleri' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Hint ve Çin Dinleri';
update public.mistakes set concept='İnançla İlgili Meseleler' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='İnançla İlgili Meseleler';
update public.mistakes set concept='İslam ve Bilim' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='İslam ve Bilim';
update public.mistakes set concept='Kur''an''a Göre Hz. Muhammed' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Kur''an''a Göre Hz. Muhammed';
update public.mistakes set concept='Kur''an''da Bazı Kavramlar' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Kur''an''da Kavramlar';
update public.mistakes set concept='İslam Düşüncesinde Tasavvufi Yorumlar' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Tasavvufi Yorumlar';
update public.mistakes set concept='Yahudilik ve Hristiyanlık' where source='meb' and exam='AYT' and subject='Din Kültürü' and concept='Yahudilik ve Hristiyanlık';
update public.mistakes set concept='Divan Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Divan Edebiyatı';
update public.mistakes set concept='Edebiyata Giriş' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Edebiyat Bilgisi ve Metin Türleri';
update public.mistakes set concept='Geçiş Dönemi Türk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Geçiş Dönemi Eserleri';
update public.mistakes set concept='Halk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Halk Edebiyatı (Âşık-Anonim)';
update public.mistakes set concept='Hikâye Türleri ve Hikâyenin Yapı Unsurları' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Hikâye';
update public.mistakes set concept='İslamiyet Öncesi Türk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='İslamiyet Öncesi Türk Edebiyatı';
update public.mistakes set concept='Millî Edebiyat Dönemi Türk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Millî Edebiyat';
update public.mistakes set concept='Öğretici Metinler' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Öğretici Metinler';
update public.mistakes set concept='Roman Türü ve Yapı Unsurları' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Roman';
update public.mistakes set concept='Servetifünun Dönemi Türk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Servet-i Fünun Edebiyatı';
update public.mistakes set concept='Şiir Bilgisi' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Şiir Bilgisi';
update public.mistakes set concept='Tanzimat Dönemi Türk Şiiri' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Tanzimat Edebiyatı';
update public.mistakes set concept='Tiyatro Türü ve Yapı Unsurları' where source='meb' and exam='AYT' and subject='Edebiyat' and concept='Tiyatro';
update public.mistakes set concept='18. Yüzyıl-19. Yüzyıl Felsefesi' where source='meb' and exam='AYT' and subject='Felsefe Grubu' and concept='19. Yüzyıl Felsefesi';
update public.mistakes set concept='20. Yüzyıl Felsefesi' where source='meb' and exam='AYT' and subject='Felsefe Grubu' and concept='20. Yüzyıl Felsefesi';
update public.mistakes set concept='MÖ 6. Yüzyıl-MS 2. Yüzyıl Felsefesi' where source='meb' and exam='AYT' and subject='Felsefe Grubu' and concept='İlk Çağ Felsefesi';
update public.mistakes set concept='MS 2. Yüzyıl-MS 15. Yüzyıl Felsefesi' where source='meb' and exam='AYT' and subject='Felsefe Grubu' and concept='Ortaçağ Felsefesi';
update public.mistakes set concept='15. Yüzyıl-17. Yüzyıl Felsefesi' where source='meb' and exam='AYT' and subject='Felsefe Grubu' and concept='Yeni Çağ Felsefesi';
update public.mistakes set concept='Atom Fiziğine Giriş ve Radyoaktivite' where source='meb' and exam='AYT' and subject='Fizik' and concept='Atom Fiziği ve Radyoaktivite';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Bağıl Hareket';
update public.mistakes set concept='Basit Harmonik Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Basit Harmonik Hareket';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Bir Boyutta Sabit İvmeli Hareket';
update public.mistakes set concept='Çembersel Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Çembersel Hareket';
update public.mistakes set concept='Modern Fizik' where source='meb' and exam='AYT' and subject='Fizik' and concept='Compton ve de Broglie';
update public.mistakes set concept='Dalga Mekaniği' where source='meb' and exam='AYT' and subject='Fizik' and concept='Dalga Mekaniği (Girişim-Kırınım-Doppler)';
update public.mistakes set concept='Elektrik ve Manyetizma' where source='meb' and exam='AYT' and subject='Fizik' and concept='Elektrik Alan ve Potansiyel';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Enerji ve Hareket';
update public.mistakes set concept='Modern Fizik' where source='meb' and exam='AYT' and subject='Fizik' and concept='Fotoelektrik Olay';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='İki Boyutta Sabit İvmeli Hareket';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='İtme ve Momentum';
update public.mistakes set concept='Elektrik ve Manyetizma' where source='meb' and exam='AYT' and subject='Fizik' and concept='Kondansatörler';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Kuvvet, Tork ve Denge';
update public.mistakes set concept='Elektrik ve Manyetizma' where source='meb' and exam='AYT' and subject='Fizik' and concept='Manyetizma ve İndüksiyon';
update public.mistakes set concept='Modern Fiziğin Teknolojideki Uygulamaları' where source='meb' and exam='AYT' and subject='Fizik' and concept='Modern Fiziğin Teknolojideki Uygulamaları';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Newton''un Hareket Yasaları';
update public.mistakes set concept='Modern Fizik' where source='meb' and exam='AYT' and subject='Fizik' and concept='Özel Görelilik';
update public.mistakes set concept='Kuvvet ve Hareket' where source='meb' and exam='AYT' and subject='Fizik' and concept='Vektörler';
update public.mistakes set concept='Analitik Düzlemde Temel Dönüşümler' where source='meb' and exam='AYT' and subject='Geometri' and concept='Analitik Düzlemde Temel Dönüşümler';
update public.mistakes set concept='Doğrunun Analitik İncelenmesi' where source='meb' and exam='AYT' and subject='Geometri' and concept='Analitik Geometri (Doğru)';
update public.mistakes set concept='Çemberin Analitik İncelenmesi' where source='meb' and exam='AYT' and subject='Geometri' and concept='Çemberin Analitik İncelenmesi';
update public.mistakes set concept='Katı Cisimler (Küre, Silindir, Koni)' where source='meb' and exam='AYT' and subject='Geometri' and concept='Katı Cisimler (Piramit-Koni-Küre)';
update public.mistakes set concept='Katı Cisimler (Küre, Silindir, Koni)' where source='meb' and exam='AYT' and subject='Geometri' and concept='Katı Cisimler (Prizma-Silindir)';
update public.mistakes set concept='Organik Bileşikler' where source='meb' and exam='AYT' and subject='Kimya' and concept='Aldehit ve Ketonlar';
update public.mistakes set concept='Organik Bileşikler' where source='meb' and exam='AYT' and subject='Kimya' and concept='Alkoller ve Eterler';
update public.mistakes set concept='Kimya ve Elektrik' where source='meb' and exam='AYT' and subject='Kimya' and concept='Elektrokimyasal Hücreler ve Piller';
update public.mistakes set concept='Kimya ve Elektrik' where source='meb' and exam='AYT' and subject='Kimya' and concept='Elektroliz';
update public.mistakes set concept='Enerji Kaynakları ve Bilimsel Gelişmeler' where source='meb' and exam='AYT' and subject='Kimya' and concept='Enerji Kaynakları';
update public.mistakes set concept='Gazlar' where source='meb' and exam='AYT' and subject='Kimya' and concept='Gazlar';
update public.mistakes set concept='Organik Bileşikler' where source='meb' and exam='AYT' and subject='Kimya' and concept='Hidrokarbonlar';
update public.mistakes set concept='Organik Bileşikler' where source='meb' and exam='AYT' and subject='Kimya' and concept='Karboksilik Asitler ve Esterler';
update public.mistakes set concept='Karbon Kimyasına Giriş' where source='meb' and exam='AYT' and subject='Kimya' and concept='Karbon Kimyasına Giriş (Hibritleşme)';
update public.mistakes set concept='Kimyasal Tepkimelerde Denge' where source='meb' and exam='AYT' and subject='Kimya' and concept='Kimyasal Tepkimelerde Denge';
update public.mistakes set concept='Kimyasal Tepkimelerde Enerji' where source='meb' and exam='AYT' and subject='Kimya' and concept='Kimyasal Tepkimelerde Enerji';
update public.mistakes set concept='Kimyasal Tepkimelerde Hız' where source='meb' and exam='AYT' and subject='Kimya' and concept='Kimyasal Tepkimelerde Hız';
update public.mistakes set concept='Modern Atom Teorisi' where source='meb' and exam='AYT' and subject='Kimya' and concept='Modern Atom Teorisi';
update public.mistakes set concept='Kimya ve Elektrik' where source='meb' and exam='AYT' and subject='Kimya' and concept='Redoks Tepkimeleri';
update public.mistakes set concept='Sıvı Çözeltiler ve Çözünürlük' where source='meb' and exam='AYT' and subject='Kimya' and concept='Sıvı Çözeltiler ve Çözünürlük';
update public.mistakes set concept='Deneysel ve Teorik Olasılık' where source='meb' and exam='AYT' and subject='Matematik' and concept='Binom ve Olasılık';
update public.mistakes set concept='Diziler' where source='meb' and exam='AYT' and subject='Matematik' and concept='Diziler';
update public.mistakes set concept='İkinci Dereceden Eşitsizlikler' where source='meb' and exam='AYT' and subject='Matematik' and concept='Eşitsizlikler';
update public.mistakes set concept='Fonksiyonların Grafik ve Problemleri' where source='meb' and exam='AYT' and subject='Matematik' and concept='Fonksiyonlarda Uygulamalar (Ters-Bileşke)';
update public.mistakes set concept='Fonksiyonların Dönüşümleri' where source='meb' and exam='AYT' and subject='Matematik' and concept='Fonksiyonların Dönüşümleri';
update public.mistakes set concept='İkinci Dereceden Fonksiyonlar ve Grafikleri' where source='meb' and exam='AYT' and subject='Matematik' and concept='İkinci Dereceden Denklemler';
update public.mistakes set concept='Belirsiz İntegral' where source='meb' and exam='AYT' and subject='Matematik' and concept='İntegral';
update public.mistakes set concept='Belirli İntegral ve Alan Hesabı' where source='meb' and exam='AYT' and subject='Matematik' and concept='İntegral ile Alan Hesabı';
update public.mistakes set concept='Trigonometrik Fonksiyonlar' where source='meb' and exam='AYT' and subject='Matematik' and concept='Kosinüs ve Sinüs Teoremi';
update public.mistakes set concept='Limit ve Süreklilik' where source='meb' and exam='AYT' and subject='Matematik' and concept='Limit ve Süreklilik';
update public.mistakes set concept='Logaritma Fonksiyonu' where source='meb' and exam='AYT' and subject='Matematik' and concept='Logaritma';
update public.mistakes set concept='İkinci Dereceden Fonksiyonlar ve Grafikleri' where source='meb' and exam='AYT' and subject='Matematik' and concept='Parabol';
update public.mistakes set concept='Trigonometrik Fonksiyonlar' where source='meb' and exam='AYT' and subject='Matematik' and concept='Sinüs ve Kosinüs Fonksiyonlarının Grafikleri';
update public.mistakes set concept='Trigonometrik Fonksiyonlar' where source='meb' and exam='AYT' and subject='Matematik' and concept='Ters Trigonometrik Fonksiyonlar';
update public.mistakes set concept='Toplam-Fark ve İki Kat Açı Formülleri' where source='meb' and exam='AYT' and subject='Matematik' and concept='Trigonometri: Toplam-Fark ve İki Kat Açı';
update public.mistakes set concept='Yönlü Açılar' where source='meb' and exam='AYT' and subject='Matematik' and concept='Trigonometri: Yönlü Açılar';
update public.mistakes set concept='Trigonometrik Denklemler' where source='meb' and exam='AYT' and subject='Matematik' and concept='Trigonometrik Denklemler';
update public.mistakes set concept='Türev' where source='meb' and exam='AYT' and subject='Matematik' and concept='Türev';
update public.mistakes set concept='Türev Uygulamaları' where source='meb' and exam='AYT' and subject='Matematik' and concept='Türev Uygulamaları (Optimizasyon)';
update public.mistakes set concept='Atatürkçülük ve Türk İnkılabı' where source='meb' and exam='AYT' and subject='Tarih' and concept='Atatürkçülük ve Türk İnkılabı';
update public.mistakes set concept='Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti (1595-1774)' where source='meb' and exam='AYT' and subject='Tarih' and concept='Değişen Dünya Dengeleri ve Osmanlı Siyaseti (1595-1774)';
update public.mistakes set concept='Değişim Çağında Avrupa ve Osmanlı' where source='meb' and exam='AYT' and subject='Tarih' and concept='Değişim Çağında Avrupa ve Osmanlı';
update public.mistakes set concept='Devrimler Çağında Değişen Devlet-Toplum İlişkileri' where source='meb' and exam='AYT' and subject='Tarih' and concept='Devrimler Çağı';
update public.mistakes set concept='II. Dünya Savaşı Sürecinde Türkiye ve Dünya' where source='meb' and exam='AYT' and subject='Tarih' and concept='II. Dünya Savaşı';
update public.mistakes set concept='İki Savaş Arasındaki Dönemde Türkiye ve Dünya' where source='meb' and exam='AYT' and subject='Tarih' and concept='İki Savaş Arası Dönem';
update public.mistakes set concept='Millî Mücadele' where source='meb' and exam='AYT' and subject='Tarih' and concept='Millî Mücadele';
update public.mistakes set concept='XIX. ve XX. Yüzyılda Değişen Sosyo-Ekonomik Hayat' where source='meb' and exam='AYT' and subject='Tarih' and concept='Sermaye ve Emek';
update public.mistakes set concept='II. Dünya Savaşı Sonrasında Türkiye ve Dünya' where source='meb' and exam='AYT' and subject='Tarih' and concept='Soğuk Savaş Dönemi';
update public.mistakes set concept='Toplumsal Devrim Çağında Dünya ve Türkiye' where source='meb' and exam='AYT' and subject='Tarih' and concept='Toplumsal Devrim Çağında Dünya ve Türkiye';
update public.mistakes set concept='Uluslararası İlişkilerde Denge Stratejisi (1774-1914)' where source='meb' and exam='AYT' and subject='Tarih' and concept='Uluslararası İlişkilerde Denge (1774-1914)';
update public.mistakes set concept='XIX. ve XX. Yüzyılda Değişen Sosyo-Ekonomik Hayat' where source='meb' and exam='AYT' and subject='Tarih' and concept='XIX-XX. Yüzyılda Gündelik Hayat';
update public.mistakes set concept='XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya' where source='meb' and exam='AYT' and subject='Tarih' and concept='XX. Yüzyıl Başlarında Osmanlı';
update public.mistakes set concept='XXI. Yüzyılın Eşiğinde Türkiye ve Dünya' where source='meb' and exam='AYT' and subject='Tarih' and concept='XXI. Yüzyılın Eşiğinde Türkiye ve Dünya';
update public.mistakes set exam='AYT', concept='Çemberde Temel Kavramlar' where source='meb' and exam='TYT' and subject='Geometri' and concept='Çember ve Daire';
commit;
